# Generated by Django 2.2.1 on 2019-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190515_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='gendle',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
