# Generated by Django 2.2.1 on 2019-05-17 08:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190516_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
