# Generated by Django 2.2.1 on 2019-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteinfo',
            name='choose1vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='choose2vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='choose1',
            field=models.CharField(max_length=10, verbose_name='选项1'),
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='choose2',
            field=models.CharField(max_length=10, verbose_name='选项2'),
        ),
    ]
